# Generated by Django 2.1.5 on 2019-04-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('birth', models.DateField()),
                ('session', models.CharField(max_length=4)),
                ('class_s', models.CharField(max_length=4)),
            ],
        ),
    ]
